version: '3.1'

services:
  motus:
    image: motus
    ports:
      - "3005:3005"
    build: 
      context: .
      dockerfile: Dockerfile-motus

  score:
    image: score
    ports: 
      - "3006:3006"
    build: 
      context: .
      dockerfile: Dockerfile-score