# syntax=docker/dockerfile:1

FROM node:16.10.0


COPY ["package.json", "package-lock.json*", "./"]

RUN npm install

RUN npm install express express-session cookie-parser

COPY . .

CMD [ "node", "script.js" ]s